# Generated by Django 6.0.5 on 2026-05-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.TextField()),
                ('base_score', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('published_date', models.DateTimeField()),
                ('last_modified_date', models.DateTimeField()),
            ],
        ),
    ]
